import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { ClerkProvider } from '@clerk/nextjs'
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/layout/app-sidebar";
import ClerkUserButton from "@/components/buttons/clerk-user-button";
import { ThemeToggle } from "@/components/buttons/theme-toggle";
import HeaderActions from "@/components/elements/header-actions";
import { currentUser } from "@clerk/nextjs/server";
import { Geologica } from "next/font/google"

const font = Geologica({ weight: "400", subsets: ["latin"], display: "swap", adjustFontFallback: false });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const user = await currentUser();
  const sidebarOpen = user ? user.unsafeMetadata.sidebarOpen as boolean : true;

  return (
    <html lang="en">
      <body className={font.className}>
        <ClerkProvider afterSignOutUrl="/sign-in">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <SidebarProvider defaultOpen={sidebarOpen}>
              <AppSidebar />
              <SidebarInset className="overflow-hidden">
                <header className="flex items-center justify-between gap-2 p-2">
                  <SidebarTrigger title="Toggle Sidebar" />
                  <ThemeToggle variant="ghost" />
                  <div className="flex-1 flex justify-end items-center gap-2">
                    <HeaderActions />
                    <div><ClerkUserButton /></div>
                  </div>
                </header>
                <div className="flex flex-1 flex-col items-center">
                  {children}
                </div>
              </SidebarInset>
            </SidebarProvider>
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
